# Generated by Django 3.2 on 2021-04-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='Description',
            field=models.CharField(default='No summary', max_length=1000),
            preserve_default=False,
        ),
    ]
