# Generated by Django 3.2 on 2021-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
