# Generated by Django 3.2 on 2021-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'pending'), ('a', 'accepted'), ('r', 'rejected')], default='p', max_length=20),
        ),
    ]
