# Generated by Django 3.2 on 2021-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'pending'), ('a', 'accepted'), ('r', 'rejected'), ('c', 'close'), ('n', 'returned')], default='p', max_length=20),
        ),
    ]
