# Generated by Django 3.2 on 2021-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='close_date',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'pending'), ('a', 'accepted'), ('r', 'rejected'), ('n', 'returned')], default='p', max_length=20),
        ),
    ]
