# Generated by Django 3.2 on 2021-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210425_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
