# Generated by Django 3.2 on 2021-04-24 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_request_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='extend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='close_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 25), null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 25), null=True),
        ),
    ]
