# Generated by Django 3.2 on 2021-04-24 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210425_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='close_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 5, 25, 2, 53, 40, 506185), null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 25, 2, 53, 40, 506185), null=True),
        ),
    ]
