# Generated by Django 3.2 on 2021-04-24 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20210425_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='close_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 25), null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 25), null=True),
        ),
    ]
