# Generated by Django 3.2 on 2021-04-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20210425_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
